# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb722c91c8ff503d661e781f154a093c09f1b1927b2a417ebff5e87af781fb297a2514ea97bf0b729768a84e50dc594faf404c9bb5d2c669f7628a58614a8e9b

test:
  secret_key_base: 6f909a6ee7523967d53d5d582f2a09aa12f0e2d9b279d504661524fdeb8cadf0237c5571ec5be48bf906e71b2dda1a9b6a5d6f934f419eee248549c2198a6775

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SOUNDISLAM_PRODUCTION_SECRET_KEY_BASE"] %>
